name: run server node

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install client dependencies
        run: cd client && npm i
        
      - name: Install sever dependencies
        run: cd client && npm i

      - name: Build Node.js app
        run: npm run build

      - name: Start Node.js server
        run: npm start &

      - name: Wait for server to start
        run: sleep 10s
